<?php

return [
    'admins' => [
        [
            'name' => 'JKrzeski',
            'email' => env('ADMIN1_EMAIL'),
            'password' => '12341234',
            'role' => 'admin', 
            'first_name' => "Jedrzej",
            'last_name' => "Krzeski",
            'phone' => '123456789',
            'country' => 'Poland',
            'city' => 'Poznań',
            'street' => 'Adminowska',
            'house_number' => '1',
            'zip_code' => '12-345',
        ],
        [
            'name' => 'JMonka',
            'email' => env('ADMIN2_EMAIL'),
            'password' => '12341234',
            'role' => 'admin',
            'first_name' => "Jacek",
            'last_name' => "Monka",
            'phone' => '123456789',
            'country' => 'Poland',
            'city' => 'Poznań',
            'street' => 'Adminowska',
            'house_number' => '2',
            'zip_code' => '12-345',
        ],
        [
            'name' => 'MBorkowski',
            'email' => env('ADMIN3_EMAIL'),
            'password' => '12341234',
            'role' => 'admin',
            'first_name' => "Mateusz",
            'last_name' => "Borkowski",
            'phone' => '123456789',
            'country' => 'Poland',
            'city' => 'Poznań',
            'street' => 'Adminowska',
            'house_number' => '3',
            'zip_code' => '12-345',
        ],
        [
            'name' => 'PGalimski',
            'email' => env('ADMIN4_EMAIL'),
            'password' => '12341234',
            'role' => 'admin',
            'first_name' => "Piotr",
            'last_name' => "Galimski", 
            'phone' => '123456789',
            'country' => 'Poland',
            'city' => 'Poznań',
            'street' => 'Adminowska',
            'house_number' => '4',
            'zip_code' => '12-345',
        ],
        [
            'name' => 'Organizer',
            'email' => 'oragnizare@eventare.com',
            'password' => '12341234',
            'role' => 'organizer',
            'first_name' => "Organizare",
            'last_name' => "Eventare", 
            'phone' => '123456789',
            'country' => 'Poland',
            'city' => 'Poznań',
            'street' => 'Kutrzeby',
            'house_number' => '10',
            'zip_code' => '61-719',
        ],
        [
            'name' => 'AdminBlogPosts',
            'email' => 'blog@admin.com',
            'password' => '12341234',
            'role' => 'blog_author',
            'first_name' => "AdminBlog",
            'last_name' => "Machen",
            'phone' => '123456789',
            'country' => 'Poland',
            'city' => 'Poznań',
            'street' => 'Adminowska',
            'house_number' => '5',
            'zip_code' => '12-345',
        ],
        [
            'name' => 'Redactor',
            'email' => 'redactor@redactor.com',
            'password' => '12341234',
            'role' => 'redactor',
            'first_name' => "Redaktor",
            'last_name' => "Machen",
            'phone' => '123456789',
            'country' => 'Poland',
            'city' => 'Poznań',
            'street' => 'Redaktorska',
            'house_number' => '1',
            'zip_code' => '12-345',
        ],
        [
            'name' => 'Moderator',
            'email' => 'moderator@moderator.com',
            'password' => '12341234',
            'role' => 'moderator',
            'first_name' => "Moderator",
            'last_name' => "Machen", 
            'phone' => '123456789',
            'country' => 'Poland',
            'city' => 'Poznań',
            'street' => 'Moderatorska',
            'house_number' => '1',
            'zip_code' => '12-345',
        ],
        [
            'name' => 'BlogAuthor',
            'email' => 'blog@author.com',
            'password' => '12341234',
            'role' => 'blog_author',
            'first_name' => "Blog",
            'last_name' => "Machen", 
            'phone' => '123456789',
            'country' => 'Poland',
            'city' => 'Poznań',
            'street' => 'Blogowa',
            'house_number' => '1',
            'zip_code' => '12-345',
        ],
            [
            'name' => 'komisja',
            'email' => 'komisja@cdv.pl',
            'password' => '12341234',
            'role' => 'admin',
            'first_name' => "Komisja",
            'last_name' => "CDV", 
            'phone' => '123456789',
            'country' => 'Poland',
            'city' => 'Poznań',
            'street' => 'Kutrzeby',
            'house_number' => '10',
            'zip_code' => '61-719',
        ],
    ],
];
