<?php

return [
    'admins' => [
        [
            'name' => 'JKrzeski',
            'email' => env('ADMIN1_EMAIL'),
            'password' => '12341234',
            'role' => 'admin', 
            'first_name' => "Jedrzej",
            'last_name' => "Krzeski",
        ],
        [
            'name' => 'JMonka',
            'email' => env('ADMIN2_EMAIL'),
            'password' => '12341234',
            'role' => 'admin',
            'first_name' => "Jacek",
            'last_name' => "Monka",
        ],
        [
            'name' => 'MBorkowski',
            'email' => env('ADMIN3_EMAIL'),
            'password' => '12341234',
            'role' => 'admin',
            'first_name' => "Mateusz",
            'last_name' => "Borkowski",
        ],
        [
            'name' => 'PGalimski',
            'email' => env('ADMIN4_EMAIL'),
            'password' => '12341234',
            'role' => 'admin',
            'first_name' => "Piotr",
            'last_name' => "Galimski", 
        ],
        [
            'name' => 'Organizer',
            'email' => 'oragnizare@eventare.com',
            'password' => '12341234',
            'role' => 'organizer',
            'first_name' => "Organizare",
            'last_name' => "Eventare", 
        ],
        [
            'name' => 'BlogAuthor',
            'email' => 'blog@author.com',
            'password' => '12341234',
            'role' => 'blog_author',
            'first_name' => "Blog",
            'last_name' => "Machen", 
        ],
        [
            'name' => 'Redactor',
            'email' => 'redactor@redactor.com',
            'password' => '12341234',
            'role' => 'redactor',
            'first_name' => "Redaktor",
            'last_name' => "Machen", 
        ],
        [
            'name' => 'Moderator',
            'email' => 'moderator@moderator.com',
            'password' => '12341234',
            'role' => 'moderator',
            'first_name' => "Moderator",
            'last_name' => "Machen", 
        ],
    ],
];
